---
- name: Check if Traefik deployment exists
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: Pod
    namespace: kube-system
    name: traefik
  register: traefik_check
  failed_when: false
  changed_when: false

- name: Disable traefik in k3s
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: absent
    api_version: apps/v1
    kind: Pod
    namespace: kube-system
    name: traefik
  when: traefik_check is defined and traefik_check.result is defined and (traefik_check.result | length > 0)

- name: Add Ingress Nginx Helm repository
  shell: |
    if ! helm repo list | awk '{print $1}' | grep -qx 'ingress-nginx'; then
      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    fi
  register: ingress_nginx_repo_result
  changed_when: false
  failed_when: ingress_nginx_repo_result.rc != 0 and 'already exists' not in ingress_nginx_repo_result.stderr

- name: Update Helm repositories
  shell: helm repo update
  changed_when: false

- name: Check if Ingress Nginx is already installed
  kubernetes.core.helm_info:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: ingress-nginx
    namespace: ingress-nginx
  register: ingress_nginx_check
  failed_when: false
  changed_when: false

- name: Install Ingress Nginx Controller
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    state: present
    values:
      controller:
        extraArgs:
          update-status: "false"
        service:
          type: LoadBalancer
  when: ingress_nginx_check.status is not defined