---
- name: Include k3s installation tasks
  include_tasks: install.yml

- name: Include Helm tasks
  include_tasks: helm.yml

- name: Include ingress tasks
  include_tasks: ingress.yml

- name: Include Monitoring tasks
  include_tasks: monitoring.yml

- name: Include UFW tasks
  include_tasks: ufw.yml