# GitHub
github_username: gutamurr
github_repo: devops-lab

# GHCR
ghcr_image: devops-lab

# Smee
smee_url: "https://smee.io/pd9T7kOLmKYblBI"

# Jenkins
jenkins_admin_username: admin
jenkins_admin_password: admin