Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-26.04"
  config.vm.box_version = "202606.01.0"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 600

  bridge_name = ENV.fetch("VAGRANT_BRIDGE", "Intel(R) Wi-Fi 6E AX210 160MHz")
  base_ip = ENV.fetch("VAGRANT_BASE_IP", "192.168.254")
  jenkins_host_port = ENV.fetch("VAGRANT_JENKINS_HOST_PORT", "8080")

  def configure_vm(vm, hostname, ip, memory, cpus, bridge_name = nil)
    vm.hostname = hostname

    if bridge_name && !bridge_name.empty?
      vm.network "public_network", ip: ip, bridge: bridge_name
    else
      # VAGRANT_BASE_IP="192.168.56" vagrant up
      vm.network "private_network", ip: ip
    end

    vm.provider "virtualbox" do |vb|
      vb.memory = memory
      vb.cpus = cpus
      vb.gui = false
      vb.name = hostname
    end
  end

  config.vm.define "jenkins-node" do |jenkins|
    configure_vm(jenkins.vm, "jenkins-node", "#{base_ip}.10", 2048, 2, bridge_name)
    jenkins.vm.network "forwarded_port", guest: 8080, host: jenkins_host_port.to_i
  end

  config.vm.define "app-node" do |app|
    configure_vm(app.vm, "app-node", "#{base_ip}.11", 4096, 4, bridge_name)
    app.vm.network "forwarded_port", guest: 80, host: 80
    app.vm.network "forwarded_port", guest: 443, host: 443
  end
end