---
  - name: Add Jenkins key
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-{{ jenkins_version }}.key
      dest: /etc/apt/keyrings/jenkins-keyring.asc
      mode: '0644'

  - name: Add Jenkins repository
    ansible.builtin.apt_repository:
      repo: >
        deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]
        https://pkg.jenkins.io/debian-stable/ binary/
      state: present
      filename: jenkins

  - name: Install Jenkins
    ansible.builtin.apt:
      name: jenkins
      state: present
      update_cache: yes
    notify:
      - Reload systemd

  - name: Ensure Jenkins service is started
    ansible.builtin.service:
      name: jenkins
      state: started
      enabled: true